# Generated by Django 4.2.7 on 2026-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_artwork_paintingword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obra de Arte', 'verbose_name_plural': 'Obras de Arte'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='canvas_data',
            field=models.TextField(help_text='Base64 del canvas pintado por el estudiante'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_limit',
            field=models.IntegerField(default=120, help_text='Tiempo en segundos (0 = sin límite)'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='condicion_valor',
            field=models.IntegerField(default=1, help_text='Valor numérico para desbloquear (ej: 5 juegos)'),
        ),
        migrations.AlterField(
            model_name='paintingword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paintingword',
            name='word',
            field=models.CharField(help_text='Palabra que el estudiante debe dibujar', max_length=100),
        ),
    ]
